### ISSUE TITLE
Has Exit Time checkbox has to be checked to prevent errors showing up in console

### ISSUE THREAD

**Issue by CuteWaterBeary** [rrazgriz/RATS#10]
If Has Exit Time is unchecked, clicking on any transition will show a double or triple error on both existing, properly working transitions, and on newly created states and transitions.

![2023-04-18-00-51-03](https://user-images.githubusercontent.com/103973703/232710914-c669bb05-73d3-4312-ae1a-5fe93c146d1a.png)

![2023-04-18-00-51-13](https://user-images.githubusercontent.com/103973703/232710608-43d27587-b6d3-4418-8a08-03c8fa91fb10.png)

Just checking off the box for Has Exit Time fixes this.

![2023-04-18-00-54-36](https://user-images.githubusercontent.com/103973703/232710394-8744c120-6825-47de-bfa0-24d887577d98.png)

**Comment by TayouVR** [comment]
that is just a warning from unity. Nothing RATS can do about it.
You can always re-enabled `Has Exit Time` on the affected states manually.

As the warning states as soon as you add a condition to your transitions it will work just fine

**Comment by CuteWaterBeary** [comment]
The transitions are already there - Unity shows no warnings unless I uncheck Has Exit Time on RATS and click back on the correctly configured states/transitions.

I believe the [  ] Has Exit time checkbox is for newly created states but it starts giving errors on every state that exists in the whole project without even creating new ones.

**Comment by rrazgriz** [comment]
This is a weird one. I think I can get around it with a quick assetdatabase check, will include in next patch.

**Comment by rrazgriz** [comment]
This should be fixed as of 1.1.2.
